version: '2.2'
services:
  mongodb:
    container_name: mongodb
    image: kumargauravgupta3/mongodb:1.0-SNAPSHOT
    ports:
      - '27018:27017'
  mysqldb:
    container_name: mysqldb
    image: kumargauravgupta3/mysqldb:1.0-SNAPSHOT
    ports:
      - '33000:3306'
    environment:
      MYSQL_DATABASE: "topspin"
      MYSQL_USER: "topspin"
      MYSQL_PASSWORD: "topspin"
      MYSQL_ROOT_PASSWORD: "root"
  discovery:
    container_name: discovery
    image: kumargauravgupta3/discovery-service-docker:1.0-SNAPSHOT
    ports:
      - '8761:8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
  config:
    container_name: config
    image: kumargauravgupta3/config-service-docker:1.0-SNAPSHOT
    ports:
      - '8888:8888'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/spring-config-service/default"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - extra=-Dspring.cloud.config.server.git.searchPaths=config-test
    links:
      - discovery
    depends_on:
      discovery:
        condition: service_healthy
  auth:
    container_name: auth
    image: kumargauravgupta3/auth-service-docker:1.0-SNAPSHOT
    ports:
      - '9001:9001'
      - '5011:5011'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 5
    links:
      - config
      - discovery
      - mongodb
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mongodb:
        condition: service_started

  user:
    container_name: user
    image: kumargauravgupta3/user-service-docker:1.0-SNAPSHOT
    ports:
      - '9002:9002'
      - '5008:5008'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002"]
      interval: 30s
      timeout: 10s
      retries: 5
    links:
      - config
      - discovery
      - mongodb
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mongodb:
        condition: service_started

  store:
    container_name: store
    image: kumargauravgupta3/store-service-docker:1.0-SNAPSHOT
    env_file:
      - id
    ports:
      - '9003:9003'
      - '5006:5006'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003"]
      interval: 30s
      timeout: 10s
      retries: 5
    links:
      - config
      - discovery
      - mongodb
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
      mongodb:
        condition: service_started

  offer:
    container_name: offer
    image: kumargauravgupta3/offer-service-docker:1.0-SNAPSHOT
    env_file:
      - id
    ports:
      - '9004:9004'
      - '5005:5005'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004"]
      interval: 30s
      timeout: 10s
      retries: 5
    links:
      - config
      - discovery
      - store
      - mysqldb
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
      store:
        condition: service_healthy